language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE palettepicker;' -U postgres
  - knex migrate:latest --env=test
  - knex seed:run --env=test
notifications:
  email: false