language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettepicker;' -U postgres
- knex migrate:latest --env=test
- knex seed:run --env=test
notifications:
  email: false
deploy:
  api_key:
    secure: KJdScMC8yfRDa4mKttnVCBKj6pUnCNMc1zhQYuLRKgRLTEuE4Ue8ydup3A3aPUKdiPyFX+hUTZt4rCtca2VNY3vu4i/fJQW+xzzRQHZo4+2Bgo89CXOBBOs7pNh5Jh8wd4kQRLGNwgJ1vFam9rHMq2sgsnuK3wCaHFSDAxpGtK4Re5DOzRdBKHZIvbs7Vea8wDdA5R9vi77wq3544ZFynuCxHJtc8CSn4IXIs0h6wYjnuAa3yppDiHGbh/jQlSghw+/nIBKqn0IrXG8xpYAguY62V7WA9R1EojEKaj/EytfYiRVlG9yOxxvJ0rpgEJkbM8N5pKIgKhdXnnUddv86VkrNgamF2PMMErLfmKqSZUXrJKANayiMJjrULCdAcuAUmQ3DV1syAQsDE998kESlu/p+Tyx3wYPUw/XE6OFSxUhhcM55HucahUcXhzBXLyCuz7ySI67tXf1STqPPUydsMdfmqgBbRRwRpQx2ZrSO7065fdDYOcQS+BePMExJ71ONeu9+a0G7PtBBtdGWltoKmecpXZmWnkJYxQvLbKJ01M4Q8U4MsvtF6FSOLdKimaXjCUA3iQebcntDkaHQxqBQdVesSpin/N0LNh32ht36YwJybtgJOll/aFjt0ni/WgTh3Clt0l3xZ6jXqs+BFYwlTJiKWvgZVXEvU45AWIbEx6o=
  app: palette-selector
  skip_cleanup: true